### ISSUE TITLE
[BUG] performance test is failing following timestamp sync change sof#8480

### ISSUE THREAD

**Issue by btian1** [thesofproject/sof-test#1153]
**Describe the bug**
CI build performance test is failing

**To Reproduce**
use local mtrace and dmesg file can reproduce as well

**Reproduction Rate**
100%.

**Expected behavior**

**Impact**
CI performance build test should pass.

**Environment**
1) Branch name and commit hash of the 2 repositories: sof (firmware/topology) and linux (kernel driver).
    * Kernel: since ww02.2
    * SOF: since ww02.2
2) Name of the topology file
    * Topology: default
3) Name of the platform(s) on which the bug is observed.
    * Platform: mtl

![image](https://github.com/thesofproject/sof/assets/17277136/322ff837-2a26-4a43-b90d-5ec97150aec4)

**Comment by aiChaoSONG** [comment]
>@aiChaoSONG was --skip-trace always useless from the beginning? If not, what other change made --skip-trace already useless before Rander's timestamp change?

The several lines of trace at the beginning in a test belongs to the previous test, that's why we want to skip them.  Before Rander's patch, there's a clear division you can tell start from where, the traces belong to current test, but after Rander's patch, you can't.
In CI, we set --skip-trace, so all traces are skipped after Rander's patch, that's why the test case failed.

**Comment by marc-hb** [comment]
Thanks @aiChaoSONG , this is useful. So you added the `--skip-to-first-trace` just for trying to be very conservative / risk-averse but you never saw this option actually pollute test results? Or barely? Or only in people's local workspace but not in CI? Thanks for sharing.

**Comment by marc-hb** [comment]
> but after Rander's patch, you can't.

Actually, we could/should probably use something like this
- https://github.com/thesofproject/linux/pull/4726

This would help not just with the logs, it would also ensure the FW itself is measured in a "clean" state.

**Comment by aiChaoSONG** [comment]
@marc-hb If test case is run by developer manually, before Rander's patch, timestamp is always start from 0, so with/without this option won't make any difference. But after Rander's patch, it will fail because the timestamp may not start from 0, and due to the mechanism we use to skip trace, no trace will left for analysis in the end. So removing the use of `--skip-to-first-trace` is a simple way to make the test case functioning, you see, we don't have good solution to **remove traces from last test** after Rander's change

**Comment by marc-hb** [comment]
> we don't have good solution to remove traces from last test after Rander's change

That's the impression I got, thanks for confirming. But the main question is still: how much pollution will this typically cause? If too much / too often, is there some trick we could use to reduce it?

Another option could be to disable IMR boot when testing performance, I think it shows the zero timestamp again for a few lines. Any idea how hard disabling IMR would that be?

**Comment by aiChaoSONG** [comment]
> how much pollution will this typically cause?
Not that much. Normally the residue traces are related to trigger stop IPC, dma put and component reset (as you can see). There could be 10 ~ 20 lines, but they won't affect performance measurement, because we focus on trace lines that are within the component log context and printed by comp_copy function in performance measurement.  So, even with the traces from previous test, it is all good.

> Any idea how hard disabling IMR would that be?
We have a kernel option sof_debug, one of its bit is used to control boot from IMR or not. But we have to set it only for performance test in deployment, which is more complex.

I think remove the use of --skip-to-first-trace is still the fastest and simplest way to workaround the current dilemma with barely negative impact.

**Comment by marc-hb** [comment]
https://github.com/orgs/community/discussions/66741

**Comment by marc-hb** [comment]
test has been passing for a while https://sof-ci.ostc.intel.com/#/result/planresultdetail/40027
