### ISSUE TITLE
[discussion] runtime pm status check may need update

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#168]
From https://github.com/thesofproject/linux/pull/1841 @ranj063 mentioned that we should not get unsupported from acpi devices.

We may need to change the check logic for 
https://github.com/thesofproject/sof-test/blob/master/test-case/check-runtime-pm-status.sh#L58-L59

**Comment by xiulipan** [comment]
@ranj063 Please update your finding here

**Comment by Bin-QA** [comment]
So we need to mark 'acpi' direct to 'unsupported' ?
https://github.com/thesofproject/sof-test/blob/master/tools/sof-dump-status.py#L21

**Comment by xiulipan** [comment]
@Bin-QA Let wait the update from @ranj063, she will check if we wrongly use the pm_status on ACPI device with the change of https://github.com/thesofproject/linux/pull/1841

**Comment by ranj063** [comment]
@xiulipan it looks like the module /driver status is inconsistent so instead of "/sys/module/snd_sof_acpi/drivers/platform:sof-audio-acpi/80860F28\:01/power/runtime_status"
we should use: "/sys/bus/acpi/devices/80860F28\:01/power/runtime_status".

On my system, both with and without this PR, the module runtime_status is always "suspended" whereas the device runtime_status is "unsupported"

**Comment by aiChaoSONG** [comment]
@xiulipan In my opinion,  as we only have three legacy platforms, and later platforms all support runtime PM, so mark ACPI platforms directly to unsupported saves a bunch of time and effort.  We don't need so scalable here.

**Comment by ranj063** [comment]
@xiulipan can we please fix this asap?

**Comment by Bin-QA** [comment]
Patch already merged
