### ISSUE TITLE
[TEST] unit test for our lib

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#370]
From https://github.com/thesofproject/sof-test/pull/369 and https://github.com/thesofproject/sof-test/pull/367
I see we may need to have some unit test for our lib.

If we do not cover all the fail cases in our lib, the test case may get into exception or give false success or false fail.

**Comment by marc-hb** [comment]
I don't think we need unit tests for "sudo". When sudo fails many tests fail with very obvious error messages, that's how I found #367 and #369. The reason no one found #367 and #369 earlier is because too few people use sof-test and that's what we've been working on: making sof-test more robust and user-friendly so more people use it more often.

**Comment by marc-hb** [comment]
Low priority, closing
