### ISSUE TITLE
Auxiliary devices in SOF break check-ipc-flood.sh (IPC3)

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#467]
Auxiliary devices in SOF thesofproject/linux#2501 break check-ipc-flood.sh https://sof-ci.01.org/sofpr/PR3545/build7503/devicetest/

quick check find big change in debugfs
```
/sys/kernel/debug/sof# ls
cc_version  debug  dsp  etrace  exception  filter  fw_version  hda  inbox  outbox  pp  probes  regs  snd_sof_client.ipc_test.0  snd_sof_client.ipc_test.1  stream  trace
/sys/kernel/debug/sof# ls snd_sof_client.ipc_test.*
snd_sof_client.ipc_test.0:
ipc_flood_count  ipc_flood_duration_ms

snd_sof_client.ipc_test.1:
ipc_flood_count  ipc_flood_duration_ms
```
- https://github.com/thesofproject/sof/pull/3545

**Comment by xiulipan** [comment]
@ranj063 could you give more info about the change here.

**Comment by fredoh9** [comment]
debugfs moved to IPC client. And by default we have two IPC test clients.
Easy solution is chaging path to first client, snd_sof_client.ipc_test.0
```
/sys/kernel/debug/sof/snd_sof_client.ipc_test.0/ipc_flood_count
echo "100000" > /sys/kernel/debug/sof/snd_sof_client.ipc_test.0/ipc_flood_count &
```

And we need to update the test case with multiple IPC clients. We can add new test case for this also.

```
# write to two ipc test client simultaneously
echo "10000" > /sys/kernel/debug/sof/snd_sof_client.ipc_test.0/ipc_flood_count &
echo "10000" > /sys/kernel/debug/sof/snd_sof_client.ipc_test.1/ipc_flood_count
```

**Comment by xiulipan** [comment]
@fredoh9 Will the path always be look like this? eg: `snd_sof_client.ipc_test.*/ipc_flood_count`
PS: if we have only one client, what will those debugfs be look like?

**Comment by ranj063** [comment]
> @fredoh9 Will the path always be look like this? eg: `snd_sof_client.ipc_test.*/ipc_flood_count`
> PS: if we have only one client, what will those debugfs be look like?

Yes. if there's only one then, you'd only see snd_sof_client.ipc_test.0

**Comment by marc-hb** [comment]
I think we will never test flood with IPC4, correct?

If correct please close as wontfix

**Comment by plbossart** [comment]
I don't know what prevents us from flooding the firmware with IPCs, regardless of the IPC type.

@ujfalusi would you agree?

**Comment by ujfalusi** [comment]
Nothing prevents us from flooding the firmware, but the flood test uses a special test IPC3 message (SOF_IPC_GLB_TEST_MSG | SOF_IPC_TEST_IPC_FLOOD), this is not present for IPC4.
I don't think this is going to be supported.

Is this really broken today for IPC3? The PR that this issue is blaming had never been merged, the sof-client infra ended up with different implementation...
Yes, you need to build the client module and make sure that it is loaded, but it should be working (for IPC3, it is not going to probe with IPC4).

**Comment by marc-hb** [comment]
Thank you for the clarifications!

IPC3 flooding has been working just fine https://sof-ci.ostc.intel.com/#/result/planresultdetail/44673

IPC4 flooding is currently skipped with the somewhat misleading "need debug firmware".
https://sof-ci.ostc.intel.com/#/result/planresultdetail/44691
There is another ticket about IPC4+flood specifically, I mixed it up with this one a bit https://github.com/thesofproject/sof-test/issues/1066
I'll see if can quickly make this message better.

> The PR that this issue is blaming had never been merged, the sof-client infra ended up with different implementation...

Great, so we can definitely close this ticket, these will never be resurrected somehow? Also, https://github.com/thesofproject/sof-test/issues/191 looks like a public duplicate? Close that too? It points at https://github.com/thesofproject/linux/pull/1841 instead of 2501. All part of the same, dead thing?

**Comment by fredoh9** [comment]
IPC flood test is not applicable to IPC4 at this moment, this is not breaking any test case any more.
How to support IPC flood test is different story/topic.

**Comment by fredoh9** [comment]
Oh, this is about IPC3. Anyway we can still close this as this is not the case any more.
