### ISSUE TITLE
module load/unload failed

### ISSUE THREAD

**Issue by libinyang** [thesofproject/sof-test#555]
Not sure this is a bug or we designed it on purpose.

check-kmod-load-unload.sh will fail when audio runtime suspend fails. However, I can manually unload/reload the modules successfully. This means runtime-suspend is not a blocker for the module reload.

**Comment by plbossart** [comment]
it's a problem if when doing a kmod load/unload loop the device remains active after the load. It means that something did not work well during the load -> it's a bug e.g. with reference counts not properly released on remove.

**Comment by libinyang** [comment]
> it's a problem if when doing a kmod load/unload loop the device remains active after the load. It means that something did not work well during the load -> it's a bug e.g. with reference counts not properly released on remove.

@plbossart If the device remains active after the load, this should be a bug related to runtime PM, not to the load/unload? The "reference count" should be the pre-condition of load/unload, not be the bug of load/unload?

**Comment by aiChaoSONG** [comment]
@libinyang can you still reproduce this issue? can you give more details or can we close?

**Comment by libinyang** [comment]
After I disable HDA in BIOS, it works well. 

But my question is: whether unload/load module cases failed because of run-time pm issue should be categorized into module load/unload issue? If it should be, I think we can close it.

**Comment by aiChaoSONG** [comment]
@libinyang The PM suspended status is the dependency of module load/unload, or the test case will fail. So I think yes.
As far as I can remember, we need to wait dsp to suspend, because module removing will hang if dsp is active. but if this is solved, we can do module remove directly without waiting for DSP suspended.

**Comment by libinyang** [comment]
> the dependency of module load/unload, or

@aiChaoSONG But shouldn't it be categorized into pm issue?

**Comment by libinyang** [comment]
Or set the status as SKIP as the dependency is not satisfied? What's our other cases behavior when we met such dependency issues?

**Comment by xiulipan** [comment]
@libinyang @aiChaoSONG I think this maybe related to our test scripts https://github.com/thesofproject/sof-test/blob/master/test-case/check-kmod-load-unload.sh
For those DUT that should support PM, we will wait for PM suspend to avoid issues. I think in @libinyang issue, the PM function is broken due to wrong configure that cause the kmod to fail. So I am OK to close this issue as this is root cause to be wrong configure.

In correct configuration, no PM or kmod issue should happen in this test case.

**Comment by libinyang** [comment]
close this as @xiulipan and @aiChaoSONG suggested
