### ISSUE TITLE
func_pipeline_export pipeline type update

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#71]
We would like to let the pipeline function output capture pipeline with only `capture` instead 
`capture,both`

And if we get `both` type we can still get PCM with both capture and playback.

**Comment by Bin-QA** [comment]
@xiulipan  I can add the `both` as default and hide option for the sof-tplgreader.py  
but how about this case: [simultaneous-playback-capture.sh](https://github.com/thesofproject/sof-test/blob/master/test-case/simultaneous-playback-capture.sh)  

So how many case need identify device type ??

if need hide the `both` for `multiple-pipeline-*` type case I will suggest to merge them as one script

**Comment by aiChaoSONG** [comment]
I think we should modify sof-tplgreader.py, for PCM with playback and capture, output two lines.  for special case, we can add an argument in sof-tplgreader.py, and let special case call sof-tplgreader.py to obtain "both" PCM @Bin-QA @xiulipan

**Comment by xiulipan** [comment]
@aiChaoSONG @Bin-QA Yes, let's split the PCM from very beginning. The both will also output some PCM if it has both capture and playback.

EG If we have `PCM0P PMC0C PCM1P PCM2C` in card 0
with `playback` we should get `hw:0,0 hw:0,1`
with `capture` we should get `hw:0,0 hw:0,2`
with `both` we should get `hw:0,0`

So case that need to use both like : simultaneous-playback-capture.sh we still use both type.
But for other test that need some playback or capture, let's try to remove the both

**Comment by Bin-QA** [comment]
@xiulipan so this change just effect export `-e` option?

**Comment by xiulipan** [comment]
@Bin-QA I think this will also need some change from tplg-reader?

**Comment by Bin-QA** [comment]
@xiulipan @aiChaoSONG 
I think here will have 3 option:  
1. just modify [func_pipeline_export](https://github.com/thesofproject/sof-test/blob/master/case-lib/pipeline.sh#L33) to add `both` keyword as default option, without python refer script change
```
    # create filter option string
    if [ $# -ne 0 ]; then
        opt="-f"
        while [ $# -ne 0 ]
        do
            opt=$opt" $1"
            shift
        done
    fi
```
2. modify sof-tplgreader.py to add `both` as default option of [filter](https://github.com/thesofproject/sof-test/blob/master/tools/sof-tplgreader.py#L209) refer keyword is type
```
    if ret_args['filter'] is not None and len(ret_args['filter']) > 0:
        for emStr in ret_args['filter']:
            key, flag, value=emStr.partition(':')
            filter_lst.append({key.strip():value.strip().replace('[','').replace(']','').split(',')})
```
3. modify tplgtool from `type` is [both](https://github.com/thesofproject/sof-test/blob/master/tools/tplgtool.py#L577)
```
    @staticmethod
    def get_pcm_type(item):
        if item["playback"] == 1 and item["capture"] == 1:
            return "both"
        if item["playback"] == 1:
            return "playback"
        if item["capture"] == 1:
            return "capture"
        return "None"
```

because current sof-tplgreader.py is not setup the `type` value, just catch from tplgtool.py  
the easy way is option 2, the least change scope is option 1  

on the other hand with this change, also need modify refer test-case for the cleanup

**Comment by aiChaoSONG** [comment]
done and close.
