### ISSUE TITLE
[BUG] envcheck.sh doesn't detect octave packages on Fedora 34

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#780]
**Describe the bug**

root@fedora sof-test]# dnf install octave-signal
Last metadata expiration check: 2:14:43 ago on Tue 05 Oct 2021 03:36:58 PM EDT.
Package octave-signal-1.4.1-8.fc34.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@fedora sof-test]# dnf install octave-io
Last metadata expiration check: 2:14:49 ago on Tue 05 Oct 2021 03:36:58 PM EDT.
Package octave-io-2.6.3-2.fc34.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@fedora sof-test]# ./env-check.sh 
Checking for some OS packages:		Warning
	Executable  sof-ctl  not found, please put sof-ctl in PATH
Optional: Octave packages are required for check-volume-levels.sh
	Please install the  octave-signal  package
	Please install the  octave-io  package

The package detection doesn't seem to work too well?

**Comment by plbossart** [comment]
it's not a package name, it's the detection that fails

```
[root@fedora sof-test]# dnf install octave octave-signal
Last metadata expiration check: 2:48:31 ago on Thu 27 Jan 2022 01:29:37 PM PST.
Package octave-6:6.4.0-1.fc35.x86_64 is already installed.
Package octave-signal-1.4.1-10.fc35.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@fedora sof-test]# dnf install octave octave-io
Last metadata expiration check: 2:48:35 ago on Thu 27 Jan 2022 01:29:37 PM PST.
Package octave-6:6.4.0-1.fc35.x86_64 is already installed.
Package octave-io-2.6.3-4.fc35.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
[root@fedora sof-test]# ./env-check.sh 
Checking for some OS packages:		pass
Optional: Octave packages are required for check-volume-levels.sh
	Please install the  octave-signal  package
	Please install the  octave-io  package
````

**Comment by marc-hb** [comment]
Oops, thanks for double checking. In fact the octave did not work on Ubuntu either!! Looks like it was never tested. Ubuntu fix submitted in #846. For Fedora, a disclaimer is printed instead.

**Comment by marc-hb** [comment]
Fedora is not "fixed" cause it's not supported but at least it's printing a warning now so it's not lying anymore

```
Optional: Octave packages are required for check-volume-levels.sh
	Not a dpkg-based OS, cannot check  octave  package
	Not a dpkg-based OS, cannot check  octave-signal  package
	Not a dpkg-based OS, cannot check  octave-io  package
```

**Comment by plbossart** [comment]
@marc-hb what makes you think Fedora is not supported? When was this decision made? We explicitly wanted sof-test to support Fedora and Chrome to make the test suite less Ubuntu-specific.

**Comment by marc-hb** [comment]
I think you're referring to my comment in this PR: https://github.com/thesofproject/sof-test/pull/846#discussion_r794685899

> If we start supporting Fedora here then we need to validate the rest of the script on Fedora too.

I was referring to the `env-check.sh` script and to this script only. Note the "build SOF" documentation is less "generous":
https://thesofproject.github.io/latest/getting_started/build-guide/build-from-scratch.html

> The following steps describe how to install the SOF development environment on Ubuntu 16.04, 18.04, 18.10, and 20.04. They should work on 19.04, 19.10 and other Linux distributions with minor or no modifications.



> We explicitly wanted sof-test to support Fedora and Chrome to make the test suite less Ubuntu-specific.

I agree 100%: for the purpose of actually _running the tests_ I will always consider supporting Fedora (and any other distro) to be top priority. Note I've submitted multiple pull requests to support Fedora and except for you I don't remember others doing much there:
- https://github.com/thesofproject/kconfig/pull/64 
- https://github.com/thesofproject/sof-docs/pull/378
- https://github.com/thesofproject/sof-test/pull/797/commits/f687b905f44970b
- https://github.com/zephyrproject-rtos/zephyr/pull/40066/commits/687ba260fecb64
- https://github.com/thesofproject/sof-bin/issues/46#issuecomment-866693171
etc.


This `env-check.sh` script is a horrible hack, even for just Ubuntu it should be rewritten (taking a lot of time). It's also a bad idea in the first place because this sort of detection and tracking changing package names is a lost cause, even on a single distribution. The much better option than a detection script like this is to make sure there is good error handling when something is missing because error handling works for everyone, not just for people runnning `env-check.sh`:

- Abort tests immediately with `set -e` when something is missing #312 
- When tests abort immediately, make sure they print a good error message, like for instance this one:
```shell
$ octave; echo $?
Command 'octave' not found, but can be installed with:
sudo apt install octave
127
```
- If the default error message is too confusing, catch the error the first time the missing tool is invoked and print a better error message than the default.

**Comment by plbossart** [comment]
solved for Ubuntu, but we still need something for Fedora.

**Comment by marc-hb** [comment]
wontfix sorry
