### ISSUE TITLE
tplgtool2.py fails with ImportError: cannot import name 'String' from 'construct'

### ISSUE THREAD

**Issue by xinato** [thesofproject/sof-test#829]
I cannot run the tplgtool2.py. I get the error:

$ ./tplgtool2.py -h

Traceback (most recent call last):

  File "/run/media/cjm/Share/sof-test/tools/./tplgtool2.py", line 11, in <module>

    from construct import this, Container, ListContainer, Struct, Const, Switch, Select, Array, Bytes, GreedyBytes, GreedyRange, FocusedSeq, Pass, Padded, Padding, Prefixed, String, Flag, Byte, Int16ul, Int32ul, Int64ul, Terminated

ImportError: cannot import name 'String' from 'construct' (/usr/lib/python3.10/site-packages/construct/__init__.py)

Construct is installed and, for example, I can import Bytes manually (via command line). But I cannot import String manually. Has String been removed from construct?

**To Reproduce**
Install prerequisites for sof-test package. Run the tplgtool2.py test.

**Expected behavior**
 Tool initializes and runs

**Comment by miRoox** [comment]
Yes, `String` has been renamed to `PaddedString` [since construct 2.9](https://construct.readthedocs.io/en/latest/transition29.html), but currently we use Ubuntu 20.04 in our CI and it uses [construct 2.8 in packages source](https://packages.ubuntu.com/focal/python3-construct), so for convenience tplgtool2.py just support construct 2.8.

Of course this is a problem, I'll perform some workaround to support different version of construct later. But for now, you can try downgrade construct package to version 2.8, otherwise you can use the legacy tplgtool.py if you don't need some new features like showing component core and dynamic pipeline.

**Comment by XiaoyunWu6666** [comment]
Please use construct 2.8.16

**Comment by xinato** [comment]
Thank you very kindly for your help, XiaoyunWu6666.

I installed the older version (2.8.16) of construct. I am still puzzled by the result. Whenever I execute the utility, I see no output. This is what I see:

(env) cjm@chromebook:~$ pip list construct
Package    Version
---------- -------
construct  2.8.16
pip        21.2.3
setuptools 57.4.0
(env) cjm@chromebook:~$ /run/media/cjm/Share/sof-test/tools/tplgtool2.py -d pcm,graph  -c always -t /lib/firmware skl_hda_dsp_generic-tplg.bin
(env) cjm@chromebook:~$ 

The help seems to work fine, but I expected to see data from the tplg file. What am I missing?

Thank yo  again.

**Comment by plbossart** [comment]
Closing, no information in 3 months
